### PR TITLE
Merge fix for demo of ngx-scanner

### PR DESCRIPTION
**Pull request by Reda1000**

### CODE REVIEW

**Comment by Reda1000** [comment]
Fixes https://github.com/zxing-js/ngx-scanner/issues/227

**Comment by odahcam** [comment]
This won't work in local environments:

```
yarn run v1.17.3
$ ng serve
An unhandled exception occurred: The src/favicon.ico asset path must start with the project source root.
See "%appdata%\Temp\ng-7IKT6S\angular-errors.log" for further details.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Reda1000** [comment]
Ok, so the ngx-scanner-stackblitz-demo is not just for stackblitz?

In this case let me check again.

**Comment by odahcam** [comment]
It was made for StackBlitz, but it would be better if it could be ran there with the same code of the official demo, my plan is to mirror the demo there, so I don't have to manually update the StackBlitz code everytime a new version of the scanner comes out.

**Comment by Reda1000** [comment]
Understood. Just tried removing root-value in angular.json on zxing-scanner-demo.

Then it works in stackblitz and locally ng-served - though I think this fix is quick and dirty. Hopefully stackblitz is going to fix.

**Comment by odahcam** [comment]
It would be nice to be able to file an issue there someway.

**Pull request merged**
